### ISSUE TITLE
NameError: name 'cancel' is not defined

### ISSUE THREAD

**Issue by BenaQ** [Its-Traadev/Fake-Verification-QR-Discord#7]
Ignoring exception in view <View timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Verify Me' emoji=None row=None>:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nextcord\ui\view.py", line 390, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\Admin\Desktop\Fake-Verification-QR-Discord-main\Fake-Verification-QR-Discord-main\main.py", line 230, in verification_callback
    c = RemoteAuthClient()
  File "C:\Users\Admin\Desktop\Fake-Verification-QR-Discord-main\Fake-Verification-QR-Discord-main\main.py", line 140, in __init__
    self._heartbeatTask = cancel()
NameError: name 'cancel' is not defined

know is this error coming, what to do?

**Comment by BenaQ** [comment]
now is this error coming, what to do?
